### PR TITLE
Acknowledge move-lang aptos and sui

### PR DESCRIPTION
**Pull request by ksolana**

### CODE REVIEW

**Comment by ksolana** [comment]
Let's use this to test the pr link. #51

**Comment by yihau** [comment]
!help

**Comment by yihau** [comment]
!add-pr-link

**Review by yihau — APPROVED** [review]

**Comment by ksolana** [comment]
working now! https://github.com/solana-labs/move/pull/287/commits/bc5d04f513f22d586f5a678c6c28952654c61694 
although we should remove the `GENERATED_BY_GITHUB_BOT` and replace with something else like PR#

**Pull request merged**
