### PR TITLE
Rebase with move-language:main branch

### PR DESCRIPTION
**Pull request by ksolana**
local testing

### CODE REVIEW

**Review by dmakarov — APPROVED** [review]
Not sure if it's feasible to review this amount of diffs. Let's assume it works, and fix issues when they arise.

**Comment by ksolana** [comment]
There are only three extra patches, others are ours.

**Comment by dmakarov** [comment]
LGTM

**Comment by ksolana** [comment]
Rebased and did a force push because there were merge conflicts preventing the merge from here.

**Pull request closed without merging**
