### PR TITLE
Documentation on toolchain update

### PR DESCRIPTION
**Pull request by ksolana**

### CODE REVIEW

**Review by dmakarov — APPROVED** [review]
I approve, but this is a bit surprising. Move build manages rust toolchain on its own, regardless of rust toolchain installed on the system (I believe).  Yesterday I merged a change in this repository that bumps rust toolchain version used by Move to 1.66, whereas active rust toolchain installed on my machine is 1.69, and the latter doesn't interfere with the toolchain version needed for Move build.

**Comment by ksolana** [comment]
When i did `cargo build` i got errors like
`error: could not rename component file from '/home/.rustup/tmp/zf6jna9jd15jb4u__dir/bk' to '/home/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/share/man'`

**Comment by dmakarov** [comment]
Interesting. It could be that there was some inconsistency in your installation of rustup working files.  Multiple toolchains coexist and managed by a single rustup installation. For example, on my system multiple toolchains installed starting from 1.65 up to 1.69 inclusively and all versions in between, and I didn't have to uninstall anything. No harm to mention uninstalling and installing in the docs, so the PR is good.

**Comment by nvjle** [comment]
> Interesting. It could be that there was some inconsistency in your installation of rustup working files. Multiple toolchains coexist and managed by a single rustup installation. For example, on my system multiple toolchains installed starting from 1.65 up to 1.69 inclusively and all versions in between, and I didn't have to uninstall anything. No harm to mention uninstalling and installing in the docs, so the PR is good.

FWIW, same here. I have numerous co-existing toolchain versions and have had no issues (no uninstall or reinstall). I'm on Ubuntu 20.04.

**Pull request merged**
