### PR TITLE
Bump rust toolchain to 1.66

### PR DESCRIPTION
**Pull request by dmakarov**

### CODE REVIEW

**Review by nvjle — APPROVED** [review]
LGTM (for other readers, we mostly discussed these changes offline in Slack).

**Comment by dmakarov** [comment]
@brson  I'd like to bump the version of rust toolchain. This is needed to be able to use solana-runtime in the testing infrastructure. solana runtime depends on some crates that seem to be incompatible with the current rust toolchain version of the move project.  Do you have any considerations against this?

**Comment by brson** [comment]
I would have preferred not to do this as it is a big divergence from upstream - now we are on a different toolchain and are carrying a big diff.

**Comment by dmakarov** [comment]
We couldn't make it work with the older rust, because of the added dependency on solana-runtime for rbpf tests.  Isn't it expected that upstream will eventually update rust toolchain version too?

**Comment by brson** [comment]
I imagine they will eventually. It's not a major problem to do this, just not ideal I think.

**Comment by nvjle** [comment]
FWIW, we did consider the potential consequences wrt to upstream divergence and decided the benefit outweighed the small cost. As some commonly used crates (e.g., cfg-expr/target-spec, guppy, etc) have been updated over time, the static Move tree is becoming more and more stale-- and we ran into a difficult dependence conflict. See my analysis of one such conflict in https://github.com/solana-labs/move/pull/162#issuecomment-1556229853.

As Dmitri notes, we essentially cannot include needed Solana dependencies-- that's prohibitively restrictive since we'll need to integrate soon (actually, this PR is one small step in that direction). Our in-house LLVM team (mostly the people in this conversation) deal with similar issues on a massively larger scale.

The good news is that the diffs are generally quite trivial (other than the one guppy API change)-- usually induced by the custom Diem clippy/lint tools complaints (e.g., "use foo instead of &foo"). These are "errors" in the Move code base itself, and would certainly have to be remedied by them at some point.

**Pull request merged**
